# Generated by Django 6.0.1 on 2026-02-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("customer", "Customer"), ("business", "Business")],
                max_length=50,
                null=True,
            ),
        ),
    ]
