# Generated by Django 6.0.1 on 2026-02-02 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth_app", "0002_alter_userprofile_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="password",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="repeated_password",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="type",
            field=models.CharField(
                choices=[("customer", "Customer"), ("business", "Business")],
                default="customer",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
