# Generated by Django 6.0.1 on 2026-02-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth_app", "0005_alter_userprofile_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tel",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="working_hours",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
